name: munir_app
description: "AI-powered assistive smart glasses for visually impaired users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:  
  flutter:
   sdk: flutter  
  flutter_localizations:  
    sdk: flutter          
  intl: ^0.20.0   

  # ðŸ”¹ Core
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_app_check: ^0.4.1+1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  cloud_functions: ^6.0.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.1
  flutter_dotenv: ^6.0.0
  timezone: ^0.9.0

  # ðŸ”¹ Auth
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0
  encrypt: ^5.0.3
  
  # ðŸ”¹ Media & Camera
  image_picker: ^1.1.2
  camera: ^0.11.1
  image: ^4.3.0
  path_provider: ^2.1.4
  flutter_tesseract_ocr: ^0.4.23

  # ðŸ”¹ Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.6.0

  # ðŸ”¹ UI / Forms
  country_picker: ^2.0.21
  dropdown_search: ^6.0.2
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1

  # ðŸ”¹ Voice & Audio
  flutter_tts: ^4.2.3
  audioplayers: ^6.1.0
  speech_to_text: ^7.0.0
  provider: ^6.1.1

  # ðŸ”¹ AI / ML
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0

  # ðŸ”¹ Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/banknote_model.tflite
    - assets/models/facenet.tflite
    - assets/models/feature_extractor.tflite
    - assets/models/mobilefacenet.tflite
    - assets/models/arcface.tflite
    - assets/models/2d106det_float16.tflite
    - assets/models/det_10g_simplified_float16.tflite
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/font/PlayfairDisplay-VariableFont_wght.ttf